site_name: My Docs
theme:
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: orange
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Main navigation menu, edit to create your sub menu; retain main menu.
nav:
    - Welcome:                              index.md
    - Tools:                                tools.md
    - Git:                                  git/git.md
    - Powershell:                           powershell.md
    - Bash:                                 bash.md
    - Cypress:                              cypress-resources/cypress.md
    - Cypress course:                       cypress-course/cypress-course.md
