site_name: My Docs
theme:
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: orange
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

# Main navigation menu, edit to create your sub menu; retain main menu.
nav:
    - Welcome:                              index.md
    - Tools:                                tools.md
    - Git:                                  git/git.md
    - Powershell:                           powershell.md
    - Bash:                                 bash.md
    - Cypress resources:                    cypress-resources/cypress.md
    - Cypress course:                       cypress-course/cypress-course.md
